"""initial schema

Revision ID: 3e26952de583
Revises:
Create Date: 2026-03-29 13:50:27.149406

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e26952de583"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracked_prs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("repo", sa.String(), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=False),
        sa.Column("integration_id", sa.String(), server_default="slack", nullable=False),
        sa.Column("message_ref", sa.String(), nullable=False),
        sa.Column("applied_emojis", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at",
            sa.String(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.String(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner", "repo", "pr_number", "integration_id", "message_ref"),
        if_not_exists=True,
    )
    with op.batch_alter_table("tracked_prs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_tracked_prs_lookup",
            ["owner", "repo", "pr_number"],
            unique=False,
            if_not_exists=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracked_prs", schema=None) as batch_op:
        batch_op.drop_index("idx_tracked_prs_lookup")

    op.drop_table("tracked_prs")
    # ### end Alembic commands ###
