"""Check that Alembic migrations are up to date with the SQLAlchemy models.

Generates a temporary autogeneration revision and inspects whether it
contains any schema operations. If it does, models have changed without
a corresponding migration being committed.
"""

import shutil
import sys
import tempfile
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory

MIGRATIONS_DIR = Path(__file__).resolve().parent.parent / "src" / "prbot" / "data" / "migrations"


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        db_path = tmp_path / "check.db"
        db_url = f"sqlite+aiosqlite:///{db_path}"

        # Copy migrations into temp dir so we don't pollute the real versions/
        tmp_migrations = tmp_path / "migrations"
        shutil.copytree(MIGRATIONS_DIR, tmp_migrations)

        cfg = Config()
        cfg.set_main_option("script_location", str(tmp_migrations))
        cfg.set_main_option("sqlalchemy.url", db_url)

        # Apply existing migrations to a temp database
        command.upgrade(cfg, "head")

        # Generate a candidate migration
        command.revision(cfg, autogenerate=True, message="check", rev_id="check")

        # Read the generated file and look for actual operations
        script_dir = ScriptDirectory.from_config(cfg)
        rev = script_dir.get_revision("check")
        if rev is None or rev.path is None:
            print("ERROR: failed to generate check revision")
            sys.exit(1)

        content = Path(rev.path).read_text()

        # Alembic wraps auto-generated ops between these markers
        marker = "# ### commands auto generated by Alembic - please adjust! ###"
        end_marker = "# ### end Alembic commands ###"

        start = content.find(marker)
        end = content.find(end_marker, start)
        if start == -1 or end == -1:
            print("ERROR: could not parse generated migration")
            sys.exit(1)

        # Extract the block between markers (after the first occurrence in upgrade)
        block = content[start + len(marker) : end].strip()

        # If the block contains only "pass" or is empty, migrations are up to date
        if block == "" or block == "pass":
            print("OK: migrations are up to date with models")
        else:
            print("FAIL: models have changed without a migration:")
            print(block)
            sys.exit(1)


if __name__ == "__main__":
    main()
